require 'require_all'
require 'active_support/inflector'
require 'sugar-high/not'
require 'sugar-high/array'
require 'sugar-high/kind_of'
require 'set'
require 'roles_generic/namespaces'
require 'roles_generic/base'
require 'roles_generic/generic'
require 'roles_generic/strategy'

